name: 🚧 Build - Build sources

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
  release:
    name: 🚧 Build
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: 🚧 Build
        uses: ./.github/actions/build

      - name: 🧪 Test
        run: |
          # =================  🧪 Test  =================
          
          pnpm run test:unit

      - name: 🧹 Eslint
        run: |
          # =================  🧹 Eslint  =================
          pnpm run lint

      - name: 🪄 Stylelint
        run: |
          # =================  🪄 Stylelint  =================
          pnpm run style