name: 🚧 Build - Build sources

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

env:
  node_version: 20.5 # see https://github.com/angular/angular-cli/issues/25782
  pnpm_version: 8.x

jobs:
  release:
    name: 🚧 Build
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4

      - name: 🚧 Build
        uses: ./.github/actions/build
        with:
          node_version: ${{ env.node_version }}
          pnpm_version: ${{ env.pnpm_version }}

      - name: 🧪 Test
        run: |
          # =================  🧪 Test  =================
          
          pnpm run test:unit

      - name: 🧹 Eslint
        run: |
          # =================  🧹 Eslint  =================
          pnpm run lint

      - name: 🪄 Stylelint
        run: |
          # =================  🪄 Stylelint  =================
          pnpm run style